[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
Host = 'localhost'
ServerBindAddr = ''  # blank value defaults to Service.Host value
Port = 49993
Protocol = 'http'
StartupMsg = 'device snmp GO started'
Timeout = 5000
ConnectRetries = 10
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false

# Pre-define Devices
# NOTE: You will need to modify the Address to a DNS or named resource potentially.
#       Port 161 is the default SNMP provider port.
[[DeviceList]]
  Name = 'trendnet01'
  Profile = 'trendnet'
  Description = 'Switch SNMP service interface'
  Labels = [ 'device-snmp-switch-example' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.TCP]
    Address = '192.168.10.200'
    Port = '161'
  [[DeviceList.AutoEvents]]
    Frequency = '10s'
    OnChange = true
    Resource = 'MacAddress'
  [[DeviceList.AutoEvents]]
    Frequency = '15s'
    OnChange = true
    Resource = 'Firmware'
  [[DeviceList.AutoEvents]]
    Frequency = '5s'
    OnChange = false
    Resource = 'Uptime'